services:
  discord_bot:
    container_name: bot
    build:
      context: .
      dockerfile: bot.Dockerfile
    networks:
      - services
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - LLM_PROVIDER=${LLM_PROVIDER}
      - OLLAMA_URL=${OLLAMA_URL}
      - OLLAMA_CHAT_MODEL=${OLLAMA_CHAT_MODEL}
      - OLLAMA_EMBEDDINGS_MODEL=${OLLAMA_EMBEDDINGS_MODEL}
      - VLLM_URL=${VLLM_URL}
      - VLLM_CHAT_MODEL=${VLLM_CHAT_MODEL}
      - MODEL2VEC_EMBEDDING_MODEL=${MODEL2VEC_EMBEDDING_MODEL}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_CHAT_MODEL=${GOOGLE_CHAT_MODEL}
      - GOOGLE_EMBEDDINGS_MODEL=${GOOGLE_EMBEDDINGS_MODEL}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION}
      - AZURE_CHAT_MODEL=${AZURE_CHAT_MODEL}
      - AZURE_EMBEDDINGS_MODEL=${AZURE_EMBEDDINGS_MODEL}
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}

  botdashboard:
    container_name: botdashboard
    build:
      context: .
      dockerfile: api.Dockerfile
    restart: unless-stopped
    networks:
      - services
    environment:  
      - DISCORD_APP_CLIENT_ID=${DISCORD_APP_CLIENT_ID}
      - DISCORD_APP_SECRET=${DISCORD_APP_SECRET}
      - REDIRECT_URI=${REDIRECT_URI}

networks:
  services:
    name: services